# TimeSeries - Reindexing and Resampling
Using our stocks data again

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_pickle('stocks.pkl')
df.head()

                  open   high    low  close   volume
Name date
A    2013-02-08  45.07  45.35  45.00  45.08  1824755
     2013-02-11  45.17  45.18  44.45  44.60  2915405
     2013-02-12  44.81  44.95  44.50  44.62  2373731
     2013-02-13  44.81  45.24  44.68  44.75  2052338
     2013-02-14  44.72  44.78  44.36  44.58  3826245

In our current data, we have business days only. What if we want the ability to look up any day in our date range and get the value? We can look back to the last trading day in this case.

To keep this simple, let's look at AAL again.

In [4]:
aal = df.loc['AAL']
aal

             open   high    low  close    volume
date
2013-02-08  15.07  15.12  14.63  14.75   8407500
2013-02-11  14.89  15.01  14.26  14.46   8882000
2013-02-12  14.45  14.51  14.10  14.27   8126000
2013-02-13  14.30  14.94  14.25  14.66  10259500
2013-02-14  14.94  14.96  13.16  13.99  31879900
...           ...    ...    ...    ...       ...
2018-02-01  54.00  54.64  53.59  53.88   3623078
2018-02-02  53.49  53.99  52.03  52.10   5109361
2018-02-05  51.99  52.39  49.75  49.76   6878284
2018-02-06  49.32  51.50  48.79  51.18   6782480
2018-02-07  50.91  51.98  50.89  51.40   4845831

[1259 rows x 5 columns]

In [5]:
start, end = aal.index.min(), aal.index.max()
print(start, end)

2013-02-08 00:00:00 2018-02-07 00:00:00

In [9]:
new_index = pd.date_range(start, end)
new_index

DatetimeIndex(['2013-02-08', '2013-02-09', '2013-02-10', '2013-02-11',
               '2013-02-12', '2013-02-13', '2013-02-14', '2013-02-15',
               '2013-02-16', '2013-02-17',
               ...
               '2018-01-29', '2018-01-30', '2018-01-31', '2018-02-01',
               '2018-02-02', '2018-02-03', '2018-02-04', '2018-02-05',
               '2018-02-06', '2018-02-07'],
              dtype='datetime64[ns]', length=1826, freq='D')

In [19]:
aal2 = aal.reindex(new_index, method='ffill')
aal2

             open   high    low  close   volume
2013-02-08  15.07  15.12  14.63  14.75  8407500
2013-02-09  15.07  15.12  14.63  14.75  8407500
2013-02-10  15.07  15.12  14.63  14.75  8407500
2013-02-11  14.89  15.01  14.26  14.46  8882000
2013-02-12  14.45  14.51  14.10  14.27  8126000
...           ...    ...    ...    ...      ...
2018-02-03  53.49  53.99  52.03  52.10  5109361
2018-02-04  53.49  53.99  52.03  52.10  5109361
2018-02-05  51.99  52.39  49.75  49.76  6878284
2018-02-06  49.32  51.50  48.79  51.18  6782480
2018-02-07  50.91  51.98  50.89  51.40  4845831

[1826 rows x 5 columns]

Great, now every date has a time. But what if we wanted to do this to all secrurities? and let's only fill within two days to cater to a weekend, but not to something more dreastic!

If we tried to use the level featureof the reindex function, we cannot use method='ffill', watch:

In [13]:
start, end = df.index.levels[1].min(), df.index.levels[1].max()
print(start, end)

2013-02-08 00:00:00 2018-02-07 00:00:00

In [17]:
date_range = pd.date_range(start, end)
date_range

DatetimeIndex(['2013-02-08', '2013-02-09', '2013-02-10', '2013-02-11',
               '2013-02-12', '2013-02-13', '2013-02-14', '2013-02-15',
               '2013-02-16', '2013-02-17',
               ...
               '2018-01-29', '2018-01-30', '2018-01-31', '2018-02-01',
               '2018-02-02', '2018-02-03', '2018-02-04', '2018-02-05',
               '2018-02-06', '2018-02-07'],
              dtype='datetime64[ns]', length=1826, freq='D')